version: "3.9"

x-airflow-common:
  &airflow-common
  build:
    context: ./
    dockerfile: ./Dockerfiles/airflow.Dockerfile
  env_file:
    - .env
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./airflow/data_raw:/opt/airflow/data_raw
    - ./airflow/dbt:/opt/airflow/dbt
    - ./profiles.yml:/home/airflow/.dbt/profiles.yml
  user: "${AIRFLOW_UID:-50000}:0"
  networks:
      - re_etl_net
  depends_on:
    &airflow-common-depends-on
    airflow_db:
      condition: service_healthy

services:
  airflow_db:
    build:
      context: ./
      dockerfile: Dockerfiles/airflow_db.Dockerfile
    shm_size: 4gb
    env_file:
      - .env
    networks:
      - re_etl_net
    ports:
      - "5432:5432"
    volumes:
      - re_airflow_db:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5
    restart: always

  dwh_db:
    build:
      context: ./
      dockerfile: Dockerfiles/postgis.Dockerfile
    shm_size: 4gb
    env_file:
      - .dwh.env
    networks:
      - re_etl_net
    ports:
      - "5431:5432"
    volumes:
      - re_dwh_db:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-p", "5431", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5
    restart: always

  db_admin:
    build:
      context: ./
      dockerfile: ./Dockerfiles/pgadmin4.Dockerfile
    env_file:
      - .env
    restart: always
    depends_on:
      - dwh_db
    networks:
      - re_etl_net
    ports:
      - "5678:80"
    volumes:
      - re_etl_admin:/var/lib/pgadmin

  dbt_proj:
    build:
      context: ./
      dockerfile: ./Dockerfiles/dbt.Dockerfile
    env_file:
      - .env
    stdin_open: true
    tty: true
    volumes:
      - ./airflow/dbt:/usr/app
      - ./profiles.yml:/root/.dbt/profiles.yml
    networks:
      - re_etl_net
    ports:
      - "18080:18080"
    depends_on:
      - dwh_db

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"']
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    # yamllint disable rule:line-length
    command:
      - -c
      - |
        function ver() {
          printf "%04d%04d%04d%04d" $${1//./ }
        }
        mkdir -p /sources/logs /sources/dags /sources/plugins /sources/data_raw /sources/dbt
        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins,data_raw,dbt}
        exec /entrypoint airflow version
    # yamllint enable rule:line-length
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
      _PIP_ADDITIONAL_REQUIREMENTS: ''
    user: "0:0"
    volumes:
      - ./airflow:/sources

  airflow-cli:
    <<: *airflow-common
    profiles:
      - debug
    environment:
      <<: *airflow-common-env
      CONNECTION_CHECK_MAX_COUNT: "0"
    # Workaround for entrypoint issue. See: https://github.com/apache/airflow/issues/16252
    command:
      - bash
      - -c
      - airflow


networks:
  re_etl_net:

volumes:
  re_airflow_db:
  re_etl_admin:
  re_dwh_db: