site_name: Analytics Data Where House Docs
theme:
  name: material
  custom_dir: docs/overrides
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
  font:
    text: Roboto
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight

repo_url: https://github.com/MattTriano/analytics_data_where_house
repo_name: MattTriano/analytics_data_where_house

nav:
  - Home: index.md
  - Setup:
    - "Overview": setup/index.md
    - 'Getting Started': setup/getting_started.md
    - 'Configure Superset': setup/superset_setup.md
    - 'Configure pgAdmin4': setup/pgAdmin4.md
  - "User's Guide":
    - user_guide/index.md
    - "Starting up the System": user_guide/system_startup.md
    - "Running a Pipeline": user_guide/running_a_pipeline.md
    - "Visualization and EDA":
      - user_guide/visualization/index.md
      - "Making Charts": user_guide/visualization/visualization.md
    - "Accessing Systems": user_guide/accessing_resources.md
  - "Developer's Guide":
    - dev_guide/index.md
    - "Adding a Socrata Pipeline": dev_guide/adding_a_socrata_pipeline.md
    - "Standardizing Columns": dev_guide/standardizing_columns.md
    - "Validating Data":
      - dev_guide/validation/index.md
      - "GE Startup": dev_guide/validation/new_workflow.md
      - "Defining a Datasource": dev_guide/validation/data_source_setup.md
      - "Setting (data) Expectations":
        - "Manual Workflow": dev_guide/validation/manually_setting_expectations.md
        - "Data Assistant Workflow": dev_guide/validation/data_assistant_workflow.md
      - "Setting Checkpoints": dev_guide/making_expectation_suites.md
    - "Engineering Features":
      - dev_guide/feature_engineering/index.md
      - "Geospatial Features": dev_guide/feature_engineering/geospatial.md
      - "Time Series Features": dev_guide/feature_engineering/time_series.md
  - "Data Sources":
    - 'Socrata ELT': data_sources/socrata.md
  - "Overview":
    - "Workflow Patterns": overview/pipeline_patterns.md

plugins:
  - search
  - glightbox

markdown_extensions:
  - toc:
      permalink: true
      separator: "_"
      toc_depth: 4
      title: On this page
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables

extra_css:
  - stylesheets/extra.css
