version: 2
sources:
  - name: data_raw
    database: re_dwh
    schema: data_raw
    tags:
      - raw
    tables:
      - name: cc_hh_earnings_in_last_12mo_by_tract
      - name: cc_hh_income_in_last_12mo_by_tract
      - name: cc_hh_internet_access_by_age_by_tract
      - name: cc_housing_occupancy_by_tract_acs5
      - name: cc_housing_tenure_single_race_by_tract_acs5
      - name: cc_housing_units_by_tract
      - name: cc_planning_db_housing_and_demos_by_bg
      - name: cc_transportation_to_work_by_occ_by_tract
      - name: chicago_affordable_rental_housing
      - name: chicago_bike_paths
      - name: chicago_building_violations
      - name: chicago_city_boundary
      - name: chicago_community_area_boundaries
      - name: chicago_crimes
      - name: chicago_cta_bus_stops
      - name: chicago_cta_train_lines
      - name: chicago_cta_train_stations
      - name: chicago_divvy_stations
      - name: chicago_dph_environmental_enforcements
      - name: chicago_food_inspections
      - name: chicago_homicide_and_shooting_victimizations
      - name: chicago_murals
      - name: chicago_police_beat_boundaries
      - name: chicago_police_district_boundaries
      - name: chicago_police_stations
      - name: chicago_potholes_patched
      - name: chicago_relocated_vehicles
      - name: chicago_shotspotter_alerts
      - name: chicago_sidewalk_cafe_permits
      - name: chicago_street_center_lines
      - name: chicago_towed_vehicles
      - name: chicago_traffic_crashes
      - name: chicago_vacant_and_abandoned_buildings
      - name: cook_county_areawaters_2022
      - name: cook_county_multifam_parcel_improvements
      - name: cook_county_neighborhood_boundaries
      - name: cook_county_parcel_assessment_appeals
      - name: cook_county_parcel_locations
      - name: cook_county_parcel_proximity
      - name: cook_county_parcel_sales
      - name: cook_county_parcel_value_assessments
      - name: cook_county_roads_2022
      - name: cook_county_sao_case_disposition_data
      - name: cook_county_sao_case_diversion_data
      - name: cook_county_sao_case_initiation_data
      - name: cook_county_sao_case_intake_data
      - name: cook_county_sao_case_sentencing_data
      - name: gross_rent_by_cook_county_il_tract
      - name: illinois_census_tracts_2022
      - name: nyc_parcel_sales
      - name: temp_cc_hh_earnings_in_last_12mo_by_tract
      - name: temp_cc_hh_income_in_last_12mo_by_tract
      - name: temp_cc_hh_internet_access_by_age_by_tract
      - name: temp_cc_housing_occupancy_by_tract_acs5
      - name: temp_cc_housing_tenure_single_race_by_tract_acs5
      - name: temp_cc_housing_units_by_tract
      - name: temp_cc_planning_db_housing_and_demos_by_bg
      - name: temp_cc_transportation_to_work_by_occ_by_tract
      - name: temp_chicago_affordable_rental_housing
      - name: temp_chicago_bike_paths
      - name: temp_chicago_building_violations
      - name: temp_chicago_city_boundary
      - name: temp_chicago_community_area_boundaries
      - name: temp_chicago_crimes
      - name: temp_chicago_cta_bus_stops
      - name: temp_chicago_cta_train_lines
      - name: temp_chicago_cta_train_stations
      - name: temp_chicago_divvy_stations
      - name: temp_chicago_dph_environmental_enforcements
      - name: temp_chicago_food_inspections
      - name: temp_chicago_homicide_and_shooting_victimizations
      - name: temp_chicago_murals
      - name: temp_chicago_police_beat_boundaries
      - name: temp_chicago_police_district_boundaries
      - name: temp_chicago_police_stations
      - name: temp_chicago_potholes_patched
      - name: temp_chicago_relocated_vehicles
      - name: temp_chicago_shotspotter_alerts
      - name: temp_chicago_sidewalk_cafe_permits
      - name: temp_chicago_street_center_lines
      - name: temp_chicago_towed_vehicles
      - name: temp_chicago_traffic_crashes
      - name: temp_chicago_vacant_and_abandoned_buildings
      - name: temp_cook_county_areawaters_2022
      - name: temp_cook_county_multifam_parcel_improvements
      - name: temp_cook_county_neighborhood_boundaries
      - name: temp_cook_county_parcel_assessment_appeals
      - name: temp_cook_county_parcel_locations
      - name: temp_cook_county_parcel_proximity
      - name: temp_cook_county_parcel_sales
      - name: temp_cook_county_parcel_value_assessments
      - name: temp_cook_county_roads_2022
      - name: temp_cook_county_sao_case_disposition_data
      - name: temp_cook_county_sao_case_diversion_data
      - name: temp_cook_county_sao_case_initiation_data
      - name: temp_cook_county_sao_case_intake_data
      - name: temp_cook_county_sao_case_sentencing_data
      - name: temp_gross_rent_by_cook_county_il_tract
      - name: temp_illinois_census_tracts_2022
      - name: temp_nyc_parcel_sales
      - name: temp_united_states_counties_2022
      - name: temp_united_states_counties_2024
      - name: temp_united_states_rails_2022
      - name: united_states_counties_2022
      - name: united_states_counties_2024
      - name: united_states_rails_2022
