version: 2
sources:
  - name: data_raw
    database: re_dwh
    schema: data_raw
    tags:
      - raw
    tables:
      - name: chicago_affordable_rental_housing
      - name: chicago_bike_paths
      - name: chicago_city_boundary
      - name: chicago_community_area_boundaries
      - name: chicago_crimes
      - name: chicago_cta_bus_stops
      - name: chicago_cta_train_stations
      - name: chicago_food_inspections
      - name: chicago_homicide_and_shooting_victimizations
      - name: chicago_police_beat_boundaries
      - name: chicago_police_district_boundaries
      - name: chicago_police_stations
      - name: chicago_potholes_patched
      - name: chicago_relocated_vehicles
      - name: chicago_shotspotter_alerts
      - name: chicago_sidewalk_cafe_permits
      - name: chicago_street_center_lines
      - name: chicago_towed_vehicles
      - name: chicago_traffic_crashes
      - name: chicago_vacant_and_abandoned_buildings
      - name: cook_county_multifam_parcel_improvements
      - name: cook_county_neighborhood_boundaries
      - name: cook_county_parcel_assessment_appeals
      - name: cook_county_parcel_locations
      - name: cook_county_parcel_sales
      - name: cook_county_parcel_value_assessments
      - name: cook_county_sao_case_disposition_data
      - name: cook_county_sao_case_diversion_data
      - name: cook_county_sao_case_initiation_data
      - name: cook_county_sao_case_intake_data
      - name: cook_county_sao_case_sentencing_data
      - name: nyc_parcel_sales
      - name: temp_chicago_affordable_rental_housing
      - name: temp_chicago_bike_paths
      - name: temp_chicago_city_boundary
      - name: temp_chicago_community_area_boundaries
      - name: temp_chicago_crimes
      - name: temp_chicago_cta_bus_stops
      - name: temp_chicago_cta_train_stations
      - name: temp_chicago_food_inspections
      - name: temp_chicago_homicide_and_shooting_victimizations
      - name: temp_chicago_police_beat_boundaries
      - name: temp_chicago_police_district_boundaries
      - name: temp_chicago_police_stations
      - name: temp_chicago_potholes_patched
      - name: temp_chicago_relocated_vehicles
      - name: temp_chicago_shotspotter_alerts
      - name: temp_chicago_sidewalk_cafe_permits
      - name: temp_chicago_street_center_lines
      - name: temp_chicago_towed_vehicles
      - name: temp_chicago_traffic_crashes
      - name: temp_chicago_vacant_and_abandoned_buildings
      - name: temp_cook_county_multifam_parcel_improvements
      - name: temp_cook_county_neighborhood_boundaries
      - name: temp_cook_county_parcel_assessment_appeals
      - name: temp_cook_county_parcel_locations
      - name: temp_cook_county_parcel_sales
      - name: temp_cook_county_parcel_value_assessments
      - name: temp_cook_county_sao_case_disposition_data
      - name: temp_cook_county_sao_case_diversion_data
      - name: temp_cook_county_sao_case_initiation_data
      - name: temp_cook_county_sao_case_intake_data
      - name: temp_cook_county_sao_case_sentencing_data
      - name: temp_nyc_parcel_sales
      - name: temp_united_states_counties_2022
      - name: united_states_counties_2022
